#!/bin/sh -e

### BEGIN INIT INFO
# Provides: vbridge-public
# Required-Start: $network vinterface-public
# Required-Stop: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Set up network bridge between host and virtual router
### END INIT INFO

BRIDGE=vbr0public
INTERFACE=vface0public

start() {
  echo "Stopping existing DHCP client"
  dhclient -r $INTERFACE || true
  if ! brctl show | grep -q $BRIDGE; then
    echo "Creating network bridge $BRIDGE"
    brctl addbr $BRIDGE
    brctl addif $BRIDGE $INTERFACE
  fi
  echo "Starting network bridge..."
  ip link set $BRIDGE up
  ip addr flush dev $INTERFACE
  ip addr flush dev $BRIDGE
  ip addr add 10.0.0.10/29 dev $BRIDGE

  ## Need to add this route and rule to ensure the subnet uses the correct gateway on router-vm
  ip route add default via 10.0.0.9 dev $BRIDGE table $BRIDGE  # Table here is named same as bridge
  ip rule add from 10.0.0.8/29 lookup $BRIDGE
}

stop() {
  if brctl show | grep -q $BRIDGE; then
    echo "Stopping network bridge..."
    ip link set $BRIDGE down
    brctl delbr $BRIDGE
  fi
}

case "$1" in
  start)
    start
    ;;

  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

