#!/bin/sh -e

### BEGIN INIT INFO
# Provides: vinterface-host
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Set up network interface for virtual net host
### END INIT INFO

INTERFACE="vface0host"

start() {
  if ! ip link show $INTERFACE &>/dev/null; then
    echo "Creating interface $INTERFACE"
    ip link add $INTERFACE type dummy
  fi
  echo "Bringing up $INTERFACE"
  ip link set $INTERFACE up
}

stop() {
  echo "Bringing down $INTERFACE..."
  ip link set $INTERFACE down
}

status() {
  ip addr show $INTERFACE
}


case "$1" in
  start)
    start
    ;;

  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0

